/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mensagram;

/**
 *
 * @author 631510047
 */
public class TelaMensagram extends javax.swing.JPanel {

    /**
     * Creates new form TelaMensagram
     */
    public TelaMensagram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRemetente = new javax.swing.JLabel();
        nomeRemetente = new javax.swing.JLabel();
        lbDestinatario = new javax.swing.JLabel();
        nomeDestinatario = new javax.swing.JLabel();
        lbEnderecoRemetente = new javax.swing.JLabel();
        lbEnderecoDestinatario = new javax.swing.JLabel();
        enderecoRemetente = new javax.swing.JLabel();
        enderecoDestinatario = new javax.swing.JLabel();
        lbObjeto = new javax.swing.JLabel();
        lbPeso = new javax.swing.JLabel();
        lbDimensao = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        lbImagem = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        btReceber = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        peso = new javax.swing.JLabel();
        dimensao = new javax.swing.JLabel();

        lbRemetente.setText("Remetente: ");

        nomeRemetente.setText("Dilma Rousseff");

        lbDestinatario.setText("Destinatário: ");

        nomeDestinatario.setText("Eduardo Cunha");

        lbEnderecoRemetente.setText("Endereço ");

        lbEnderecoDestinatario.setText("Endereço");

        enderecoRemetente.setText("Porto Alegre, Getúlio Vargas 91/15 ");

        enderecoDestinatario.setText("Porto Alegre, Visconde do Herval 517/02");

        lbObjeto.setText("Objeto");

        lbPeso.setText("Peso:");

        lbDimensao.setText("Dimensões");

        lbDescricao.setText("Descrição:");

        descricao.setText("Mouse HP - peça de computador");
        descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoActionPerformed(evt);
            }
        });

        lbImagem.setText("Imagem");

        imagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\631510047\\Desktop\\mouseHp.jpg")); // NOI18N

        btReceber.setText("Receber");

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        peso.setText("0,080kg");

        dimensao.setText("94,85 x 57 x 39,11 mm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRemetente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeRemetente))
                    .addComponent(lbEnderecoRemetente)
                    .addComponent(enderecoRemetente)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPeso)
                            .addComponent(lbDimensao)
                            .addComponent(lbDescricao))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dimensao)
                            .addComponent(peso))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoDestinatario)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDestinatario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeDestinatario))
                            .addComponent(lbEnderecoDestinatario))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btReceber)
                                .addGap(18, 18, 18)
                                .addComponent(btVoltar)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbImagem)
                                .addGap(96, 96, 96))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(lbObjeto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRemetente)
                    .addComponent(nomeRemetente)
                    .addComponent(lbDestinatario)
                    .addComponent(nomeDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnderecoRemetente)
                    .addComponent(lbEnderecoDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoRemetente)
                    .addComponent(enderecoDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbObjeto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPeso)
                    .addComponent(lbImagem)
                    .addComponent(peso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDimensao)
                            .addComponent(dimensao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btReceber)
                            .addComponent(btVoltar))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReceber;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField descricao;
    private javax.swing.JLabel dimensao;
    private javax.swing.JLabel enderecoDestinatario;
    private javax.swing.JLabel enderecoRemetente;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbDestinatario;
    private javax.swing.JLabel lbDimensao;
    private javax.swing.JLabel lbEnderecoDestinatario;
    private javax.swing.JLabel lbEnderecoRemetente;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbObjeto;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbRemetente;
    private javax.swing.JLabel nomeDestinatario;
    private javax.swing.JLabel nomeRemetente;
    private javax.swing.JLabel peso;
    // End of variables declaration//GEN-END:variables
}
